---
- name: Aplicar hardening CIS
  hosts: localhost
  become: yes
  tasks:
    - name: 1.1.1.1 - Deshabilitar filesystems no seguros
      ansible.builtin.command:
        cmd: "modprobe -n -v {{ item }} | grep -E '(cramfs|squashfs|udf)'"
      loop:
        - cramfs
        - squashfs
        - udf
      changed_when: false
      register: fs_modules

    - name: 1.1.1.2 - Bloquear filesystems no seguros
      ansible.builtin.sysctl:
        name: "kernel.module.disabled"
        value: "1"
        sysctl_set: yes
      when: fs_modules.results | map(attribute='stdout') | list | length > 0

    - name: 3.1.1 - Deshabilitar servicios inseguros
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - nfs
        - rpcbind

    - name: 5.2.1 - Configurar permisos en /etc/ssh/sshd_config
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'

    - name: Generar reporte de hardening
      ansible.builtin.copy:
        content: |
          CIS Hardening Report
          ====================
          Fecha: {{ ansible_date_time.iso8601 }}
          
          Resultados:
          - Filesystems no seguros deshabilitados: {{ fs_modules.results | map(attribute='stdout') | list | join(', ') }}
          - Servicios inseguros detenidos: nfs, rpcbind
          - Permisos SSH configurados correctamente
        dest: ./hardening-report.txt
