---
- name: Aplicar hardening CIS
  hosts: localhost
  become: yes
  tasks:
    - name: 1.1.1.1 - Verificar filesystems no seguros
      ansible.builtin.shell: |
        if lsmod | grep -q "{{ item }}"; then
          echo "{{ item }} está cargado"
          exit 1
        else
          echo "{{ item }} no está cargado"
          exit 0
        fi
      loop:
        - cramfs
        - squashfs
        - udf
      register: fs_check
      changed_when: false
      ignore_errors: true

    - name: 1.1.1.2 - Bloquear filesystems no seguros
      ansible.builtin.shell: |
        echo "install {{ item }} /bin/true" >> /etc/modprobe.d/{{ item }}.conf
        echo "blacklist {{ item }}" >> /etc/modprobe.d/{{ item }}.conf
      loop:
        - cramfs
        - squashfs
        - udf
      when: fs_check.results | selectattr('rc', 'equalto', 1) | list | length > 0

    - name: 3.1.1 - Deshabilitar servicios inseguros
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - nfs
        - nfs-server
        - rpcbind

    - name: 5.2.1 - Configurar permisos en SSH
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
      when: ansible_facts.pkg_mgr == 'apt'

    - name: 2.1.1 - Deshabilitar servicios de red innecesarios
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - avahi-daemon
        - cups
        - isc-dhcp-server
      ignore_errors: true

    - name: 1.5.1 - Configurar permisos en /boot/grub/grub.cfg
      ansible.builtin.file:
        path: /boot/grub/grub.cfg
        owner: root
        group: root
        mode: '0600'
      when: ansible_facts.pkg_mgr == 'apt'

    - name: Generar reporte de hardening
      ansible.builtin.copy:
        content: |
          CIS Hardening Report
          ====================
          Fecha: {{ ansible_date_time.iso8601 }}
          
          Resultados:
          - Filesystems no seguros verificados: 
            {% for result in fs_check.results %}
            {{ result.item }}: {{ "Bloqueado" if result.rc == 1 else "OK" }}
            {% endfor %}
          - Servicios inseguros detenidos: nfs, nfs-server, rpcbind
          - Permisos SSH configurados: {{ 'Sí' if ansible_facts.pkg_mgr == 'apt' else 'No aplica' }}
          - Servicios de red innecesarios deshabilitados: avahi-daemon, cups, isc-dhcp-server
          - Permisos de GRUB configurados: {{ 'Sí' if ansible_facts.pkg_mgr == 'apt' else 'No aplica' }}
        dest: ./hardening-report.txt
