name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Limpiar contenedores previos
        run: |
          docker ps -aq | xargs docker rm -f || true
          docker system prune -f

      - name: Iniciar app Flask
        run: |
          cd app
          pkill -f gunicorn || true
          gunicorn --bind 0.0.0.0:5000 \
                  --workers 2 \
                  --threads 4 \
                  --access-logfile - \
                  --log-level warning \
                  wsgi:app > app.log 2>&1 &
          # Espera más tiempo con más reintentos
          for i in {1..10}; do
            if curl -s --max-time 5 http://localhost:5000/health | grep healthy; then
              echo "App iniciada correctamente"
              break
            else
              echo "Intento $i: App no lista, reintentando..."
              sleep 10
            fi
          done

      - name: Verificar acceso desde contenedor (usando IP)
        run: |
          HOST_IP=$(hostname -I | awk '{print $1}')
          echo "Dirección IP del host: $HOST_IP"
          docker run --rm curlimages/curl \
            curl -v http://$HOST_IP:5000/health || (echo "ERROR: App no accesible desde contenedor" && exit 1)
    
      - name: Verificar estado de la app
        run: |
         netstat -tulnp | grep ':5000' || (echo "App no está en puerto 5000" && exit 1)
         curl -s http://localhost:5000/health | grep healthy || (cat app/app.log && exit 1)

      - name: Verificar nombres de artefactos
        run: |
          echo "Nombres de artefactos a subir:"
          echo "ZAP: zap-security-reports"
          echo "Hardening: hardening-report-artifact"

      - name: Preparar directorio de reportes ZAP
        run: |
          mkdir -p ${{ github.workspace }}/zap
          chmod 777 ${{ github.workspace }}/zap  # Dar permisos completos

      - name: Escanear con OWASP ZAP (Solución Definitiva)
        run: |
          # Obtener IP del host
          HOST_IP=$(hostname -I | awk '{print $1}')
          echo "Escaneando aplicación en: http://$HOST_IP:5000"

          # 1. Ejecutar escaneo con configuración robusta
          docker run --rm \
            --network="host" \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            -e ZAP_JVM_OPTIONS="-Xmx2g" \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
            -t http://127.0.0.1:5000 \
            -a -T 30 -s \
            -z "-config api.disablekey=true \
                -config scanner.attackOnStart=true \
                -config connection.timeoutInSecs=300 \
                -config scanner.threadPerHost=2 \
                -config domxss.scan=false \
                -config spider.maxDuration=15" \
            -r /zap/wrk/zap/zap-report.html \
            -w /zap/wrk/zap-report.md 2>&1 | tee zap-scan.log
           
          # Mostrar logs para diagnóstico
          echo "=== LOGS DEL ESCANEO ZAP ==="
          cat zap-scan.log

      - name: Verificar y completar reportes
        run: |
          echo "=== Contenido del directorio zap/ ==="
          ls -lh ${{ github.workspace }}/zap
          
          # Si los reportes están vacíos, generar contenido mínimo
          if [ ! -s "${{ github.workspace }}/zap/zap-report.html" ]; then
            echo "<html><body><h1>Error: Reporte vacío</h1><p>El escaneo no generó contenido. Verifique los logs.</p></body></html>" > ${{ github.workspace }}/zap/zap-report.html
          fi
          
          if [ ! -s "${{ github.workspace }}/zap/zap-report.md" ]; then
            echo "# Error: Reporte vacío" > ${{ github.workspace }}/zap/zap-report.md
            echo "El escaneo no generó contenido. Verifique los logs de ejecución." >> ${{ github.workspace }}/zap/zap-report.md
          fi
          
          echo "=== Tamaño de reportes ==="
          du -h ${{ github.workspace }}/zap/zap-report.html
          du -h ${{ github.workspace }}/zap/zap-report.md
      - name: Subir reportes ZAP
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-security-reports
          path: ${{ github.workspace }}/zap/
          retention-days: 7

  server-hardening:
    runs-on: ubuntu-latest
    needs: security-scan
    if: always()
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Ejecutar hardening CIS
        run: |
          cd ansible
          ansible-playbook playbook.yml -v > hardening.log 2>&1 || true
          echo "=== Reporte de Hardening ==="
          [ -f hardening-report.txt ] && cat hardening-report.txt || echo "No se generó reporte"
          [ -f hardening-report.txt ] || echo "Resultados no disponibles" > hardening-report.txt

      - name: Subir reporte de hardening
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hardening-report-artifact
          path: ansible/hardening-report.txt
          retention-days: 7

